# Copyright 2016, 2017 Peter Dimov
# Copyright 2017-2018 Kohei Takahashi
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop

platform:
  - x64

environment:
  matrix:
    - ARGS: --toolset=gcc address-model=32
      PATH: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
      TEST_SUITE: fusion_all_mingw_tests
    - ARGS: --toolset=gcc address-model=32 linkflags=-Wl,-allow-multiple-definition
      PATH: C:\MinGW\bin;%PATH%
      TEST_SUITE: fusion_all_mingw_tests
    - ARGS: --toolset=gcc address-model=64
      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
      TEST_SUITE: fusion_all_mingw_tests
    - ARGS: --toolset=gcc address-model=64 cxxflags=-std=gnu++1z
      PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
      TEST_SUITE: fusion_all_mingw_tests
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      ARGS: --toolset=msvc-9.0  address-model=32
      TEST_SUITE: fusion_all_tests
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      ARGS: --toolset=msvc-10.0 address-model=32
      CXXSTD: latest # fake
      TEST_SUITE: fusion_all_tests
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      ARGS: --toolset=msvc-11.0 address-model=32
      CXXSTD: latest # fake
      TEST_SUITE: fusion_all_tests
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      ARGS: --toolset=msvc-12.0 address-model=32
      CXXSTD: latest # fake
      TEST_SUITE: fusion_all_tests
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      ARGS: --toolset=msvc-12.0 address-model=64
      CXXSTD: latest # fake
      TEST_SUITE: fusion_all_tests
    - ARGS: --toolset=msvc-14.0 address-model=32
      TEST_SUITE: fusion_all_tests
    - ARGS: --toolset=msvc-14.0 address-model=64
      TEST_SUITE: fusion_all_tests
    - ARGS: --toolset=msvc-14.0 address-model=64 cxxflags=-std:c++latest
      TEST_SUITE: fusion_all_tests
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARGS: --toolset=msvc-14.1 address-model=32
      TEST_SUITE: fusion_all_tests
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARGS: --toolset=msvc-14.1 address-model=64
      TEST_SUITE: fusion_all_tests
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARGS: --toolset=msvc-14.1 address-model=64 cxxflags=-std:c++latest
      TEST_SUITE: fusion_all_tests

install:
  - cd ..
  - git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\fusion
  - python tools/boostdep/depinst/depinst.py fusion
  - bootstrap
  - b2 headers

build: off

test_script:
  - cd libs\config\test
  - ..\..\..\b2 config_info_travis_install %ARGS%
  - config_info_travis
  - cd ..\..\fusion\test
  - ..\..\..\b2 -j%NUMBER_OF_PROCESSORS% --hash %ARGS% %TEST_SUITE%
